baseURL = "https://dengzhao7053.github.io/blogs/"
languageCode = "en-us"
title = "My New Hugo Site"
publishDir = "docs"
theme = "hyde"
summaryLength = 1

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[params]
  themeColor = "theme-base-08"

[Menus]
  main = [
    {Name = "Series", URL = "/series"},
    {Name = "categories", URL = "/categories"},
    {Name = "Tags", URL = "/tags"}
  ]