baseURL = "https://dengzhao7053.github.io/blogs/"
languageCode = "en-us"
title = "My New Hugo Site"
publishDir = "docs"
theme = "hyde"
summaryLength = 1
hasCJKLanguage = true

[params]
  themeColor = "theme-base-08"